var CANVAS_WIDTH = 1000;
var CANVAS_HEIGHT = 700;
var TOILET_MAX_SPEED = 22;
var TIME_PER_LEVEL = 15; // 30 seconds
var TOILET_ACCELERATION = 1.45;
var PLUNGER_ACCELERATION = 1/350;
var SPRITE_IMAGE_PATH = "images";
var SOUND_FILE_PATH = "audio";